FROM python:3.12-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

WORKDIR /backend

CMD [ "python3", "app.py"]


#docker build --tag my-cool-project .

