services:
  swycle:
    image: registry.sccs.swarthmore.edu/cs77-s25/swycle/swycle:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DOMAIN: https://swycle.sccs.swarthmore.edu/
    env_file:
      - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.swycle.entrypoints=https"
        - "traefik.http.routers.swycle.rule=Host(`swycle.sccs.swarthmore.edu`)"
        - "traefik.http.routers.swycle.tls=true"
        - "traefik.http.routers.swycle.tls.certresolver=letsEncrypt"
        - "traefik.http.services.swycle.loadbalancer.server.port=5173"
    networks:
      - internal
      - traefik
    command: sh -c "sleep 5 && npm run preview -- --host --port 5173"

  swycle-backend:
    image: registry.sccs.swarthmore.edu/cs77-s25/swycle/swycle:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      CORS_ORIGIN: https://swycle.sccs.swarthmore.edu
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swycle-backend.entrypoints=https"
      - "traefik.http.routers.swycle-backend.tls=true"
      - "traefik.http.routers.swycle-backend.tls.certresolver=letsEncrypt"
      - "traefik.http.services.swycle-backend.loadbalancer.server.port=5001"
    networks:
      - internal
      - traefik

networks:
  internal:

  traefik:
    external: true
