version: "3.8"

services:
  swycle-frontend:
    image: registry.sccs.swarthmore.edu/cs77-s25/swycle-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swycle-frontend.entrypoints=https"
      - "traefik.http.routers.swycle-frontend.rule=Host(`swycle.sccs.swarthmore.edu`)"
      - "traefik.http.routers.swycle-frontend.tls=true"
      - "traefik.http.routers.swycle-frontend.tls.certresolver=letsEncrypt"
      - "traefik.http.services.swycle-frontend.loadbalancer.server.port=80"
    networks:
      - internal
      - traefik

  swycle-backend:
    image: registry.sccs.swarthmore.edu/cs77-s25/swycle-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swycle-backend.entrypoints=https"
      - "traefik.http.routers.swycle-backend.rule=Host(`swycle.sccs.swarthmore.edu`) && PathPrefix(`/api`)"
      - "traefik.http.routers.swycle-backend.tls=true"
      - "traefik.http.routers.swycle-backend.tls.certresolver=letsEncrypt"
      - "traefik.http.services.swycle-backend.loadbalancer.server.port=5000"
    networks:
      - internal
      - traefik

networks:
  internal:
  traefik:
    external: true
